package myapp;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import config.db_configuration;
import java.awt.BasicStroke;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import net.proteanit.sql.DbUtils;
import static internalPages.resident.tbl_res;


/**
 *
 * @author Mark
 */
public class updatePage extends javax.swing.JFrame {

    /**
     * Creates new form updatePage
     */
    public updatePage() {
        initComponents();
    }
      Color navcolor = new Color(69,193,255);
     Color headcolor = new Color(102,102,255);
      Color bodycolor = new Color(153,153,255);
      
         
      Color hover = new Color(0,153,255);
    Color defButton = new Color(69,193,255);
    
    Border empty = BorderFactory.createEmptyBorder();
    
    void buttonBorderAnimation(JPanel panel){
    panel.setBackground(hover);
    panel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    panel.setBorder(BorderFactory.createStrokeBorder(new BasicStroke(2.0f)));
    
    }
    
    void buttonDefaultColor(JPanel panel){
    panel.setBackground(defButton);
    panel.setBorder(empty);
    }
    
    public void displayData(){
       
        try{
       
            db_configuration dbc = new db_configuration();
            ResultSet rs = dbc.getData("SELECT * FROM tbl_resident");
            tbl_res.setModel(DbUtils.resultSetToTableModel(rs));
       
        }catch(SQLException ex){
            System.out.println("Error Message: "+ex);
       
        }
    }
     public void resetData(){
     ID.setText("");
     NAME.setText("");
     BDATE.setText("");
     CHILDREN.setText("");
     CONTACT.setText("");
     rd_gender.clearSelection();
     cb_status.setSelectedIndex(0);
     cb_purok.setSelectedIndex(0);
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        rd_gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        navBar = new javax.swing.JPanel();
        CONTACT = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        NAME = new javax.swing.JTextField();
        BDATE = new javax.swing.JTextField();
        CHILDREN = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        cb_status = new javax.swing.JComboBox<>();
        cb_purok = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navBar.setBackground(new java.awt.Color(69, 193, 215));
        navBar.setLayout(null);

        CONTACT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        navBar.add(CONTACT);
        CONTACT.setBounds(300, 110, 210, 30);

        ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        navBar.add(ID);
        ID.setBounds(40, 40, 210, 30);

        NAME.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NAMEActionPerformed(evt);
            }
        });
        navBar.add(NAME);
        NAME.setBounds(40, 100, 210, 30);

        BDATE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        navBar.add(BDATE);
        BDATE.setBounds(40, 160, 210, 30);

        CHILDREN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        navBar.add(CHILDREN);
        CHILDREN.setBounds(300, 50, 210, 30);

        jButton1.setText("UPDATE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        navBar.add(jButton1);
        jButton1.setBounds(420, 210, 90, 30);

        jPanel2.setBackground(new java.awt.Color(69, 193, 215));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("x");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 30, 50));

        navBar.add(jPanel2);
        jPanel2.setBounds(520, 0, 30, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("ID");
        navBar.add(jLabel2);
        jLabel2.setBounds(40, 20, 40, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("NAME");
        navBar.add(jLabel3);
        jLabel3.setBounds(40, 80, 50, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("CONTACT");
        navBar.add(jLabel4);
        jLabel4.setBounds(300, 90, 80, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("CHILDREN");
        navBar.add(jLabel8);
        jLabel8.setBounds(300, 30, 80, 20);

        male.setBackground(new java.awt.Color(69, 193, 215));
        male.setText("Male");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, male, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), male, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        male.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                maleStateChanged(evt);
            }
        });
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        navBar.add(male);
        male.setBounds(40, 210, 80, 30);

        female.setBackground(new java.awt.Color(69, 193, 215));
        female.setText("Female");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, female, org.jdesktop.beansbinding.ELProperty.create("${actionCommand}"), female, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        navBar.add(female);
        female.setBounds(120, 210, 100, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("BDATE");
        navBar.add(jLabel6);
        jLabel6.setBounds(40, 140, 50, 20);

        cb_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STATUS", "Single", "Married", "Widow", "Engaged" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cb_status, org.jdesktop.beansbinding.ELProperty.create("${selectedItem}"), cb_status, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        navBar.add(cb_status);
        cb_status.setBounds(300, 160, 100, 30);

        cb_purok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PUROK", "Dolphin", "Bolinao", "Mamsa", "Tangigue", "Tulingan", "Solid" }));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, cb_purok, org.jdesktop.beansbinding.ELProperty.create("${selectedItem}"), cb_purok, org.jdesktop.beansbinding.BeanProperty.create("selectedItem"));
        bindingGroup.addBinding(binding);

        navBar.add(cb_purok);
        cb_purok.setBounds(406, 160, 100, 30);

        jPanel1.add(navBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       db_configuration dbc = new db_configuration();
        int num = dbc.updateData("UPDATE tbl_resident "
               
                + "SET res_name = '"+NAME.getText()+"', "
                + "res_bdate='"+BDATE.getText()+"', "
                + "res_status ='"+cb_status.getSelectedItem().toString()+ "', "
              //  + "res_gender ='"+rd_gender.getSelection().getActionCommand()+"', "
                + "res_child='"+CHILDREN.getText()+"',res_contact ='"+CONTACT.getText()+"', "
                + "res_purok ='"+cb_purok.getSelectedItem().toString()+"' "
                + "WHERE res_id = '"+ID.getText()+"'");
       
             resetData();
           JOptionPane.showMessageDialog(null, "Updated Successfully!");
           displayData();
          this.dispose();
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
       this.dispose();
    }//GEN-LAST:event_jPanel2MouseClicked

    private void NAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NAMEActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
       female.setSelected(false);
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        male.setSelected(false);
    }//GEN-LAST:event_femaleActionPerformed

    private void maleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_maleStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_maleStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updatePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updatePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updatePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updatePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new updatePage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField BDATE;
    public static javax.swing.JTextField CHILDREN;
    public static javax.swing.JTextField CONTACT;
    public static javax.swing.JTextField ID;
    public static javax.swing.JTextField NAME;
    public static javax.swing.JComboBox<String> cb_purok;
    public static javax.swing.JComboBox<String> cb_status;
    public static javax.swing.JRadioButton female;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JRadioButton male;
    private javax.swing.JPanel navBar;
    private javax.swing.ButtonGroup rd_gender;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
